### ISSUE TITLE
dont work with transfers

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/PocketMine-0.13.0#15]

**Comment by keithkfng** [comment]
Let us start on the basics first please. Did you try and use @PEMapModder's quick fix?

**Comment by deotern** [comment]
Tried, not working.... @PEMapModder's quick fix is to close RakLib connection
Now, the bug is, player didn't even get transferred

**Comment by keithkfng** [comment]
I have asked MrGenga about it, see what he can do.

**Comment by XFuryMCPE** [comment]
They were removed from mcpe completely. FastTransfer won't work. Not an issue with this PM Version I don't think..

**Comment by keithkfng** [comment]
We will look into this issue.

**Comment by deotern** [comment]
@XFuryMCPE Where did u saw the news that they said "they removed from mcpe completely", how do u know this? and saw this

**Comment by jojoe77777** [comment]
@deotern Quoted from PEMapModder:
`Some rumours (not proved or disproved yet) say that it is going to get completely removed in 0.13` (talking about the Strange(Transfer)Packet)

**Comment by deotern** [comment]
.... So, can someone prove this statement?
Because i searched and seems to MCPE transfer Protocol still there (0x1b)

**Comment by keithkfng** [comment]
I believe this packet hasn't been removed, and is just a rumour. Somebody will fix it eventually(I hope).

**Comment by PEMapModder** [comment]
@deotern by investigating the disassembled 0.13

**Comment by reidq7** [comment]
Does that mean just FastTransfer will not work? Is it still possible to find a way to transfer players?

**Comment by deotern** [comment]
@reidq7 Yes, FastTransfer won't be worked...

**Comment by keithkfng** [comment]
@zombie_Power from PocketMine Forums is trying to make s fix. Hopefully, he makes a successful attempt.

**Comment by PEMapModder** [comment]
No. It is still possible with a proxy, but then it's no longer "transferring".

**Comment by reidq7** [comment]
"Transferring" meaning what? Why is it different from a proxy?

**Comment by reidq7** [comment]
Is this an impossibility question or just that no one has released anything?

**Comment by PEMapModder** [comment]
Transferring is like the Location header in HTTP. You send a signal to MCPE and MCPE disconnects and go to another server.

A proxy is basically forwarding. You join, for example, a.example.com and it actually forwards your packets to b.example.com, and when told to do so, forwards them to c.example.com instead.

**Comment by keithkfng** [comment]
Can you help us fix this PLEASE

**Comment by PEMapModder** [comment]
There is no fix. If you are using the proxy method, then the proxy server isn't even part of the main server.

**Comment by keithkfng** [comment]
Which means you can't transfer players anymore?

**Comment by reidq7** [comment]
So I'm picturing it as:  Only one set of worlds and plugins can be connected to, but they can connect to it using different servers to reduce lag?

**Comment by deotern** [comment]
You can only transfer player when it hasn't reached the server yet :)

**Comment by keithkfng** [comment]
So there is no fix, and FastTransfer won't work. The only solution is a proxy server as mentioned by @PEMapModder. Can we create that proxy server ourselves and distribute it to the public, or does everyone need to do that themselves?

**Comment by PEMapModder** [comment]
It seems like you don't even understand how FastTransfer worked.

In 0.11, FastTransfer sends a packet to the client, containing the address and the port. The client will disconnect from the current server and then go to that address and port after receiving the packet.
In 0.12, not sure what the reason was, the client no longer disconnects from the old server. This can be semi-fixed by telling the old server to reject packets from the client.
In 0.13, the client completely ignores the packet.

Note that in 0.11 and 0.12, the client voluntarily joins the new server.
It is like a postman asked you to receive a package. You are the server and the postman is the client. Transferring a client is like telling the postman to send the package to another house. In 0.11, the postman will leave and go to that other house. In 0.12, the postman keeps knocking your door to tell you to receive, but also sends a clone to knock that other house's door. In 0.13, the postman completely ignores what you say. He will not knock the door of the other house but keep telling you to receive the package.
A proxy server is like a central postbox of your building. After the postman sends a package, the proxy server will not reject it but will take the package and decide who should receive the package.

**Comment by PEMapModder** [comment]
Was planning to develop a proxy server called [Amoeba](/LegionPE/Amoeba-Server).

**Comment by deotern** [comment]
This can be a solution, but... It cant be prefect, as it CAN'T transfer player when you already joined to a server... But im quite curious about Hypixel, how Hypixel will handle this... :/

**Comment by PEMapModder** [comment]
It can.

**Comment by keithkfng** [comment]
That'd be nice, to help our everyone.

**Comment by deotern** [comment]
Can? how? xD
Ops, *sorry for closing

**Comment by PEMapModder** [comment]
If it can't, Amoeba will be much easier to code.

**Comment by deotern** [comment]
Hahaha
Seriously? @PEMapModder Yours repo name always related with biology xD

**Comment by keithkfng** [comment]
You haven't joined the organisation yet @PEMapModder XD

**Comment by PEMapModder** [comment]
Amoeba-Server acts like an independent server. It will handle your login handshake packets until the MCPE_LOGIN_PACKET is received, at which it would send a "nerve impulse" to a pseudopodium (a child server) that tells it to start the player's session and start forwarding the packets.

**Comment by deotern** [comment]
Sounds good, how can we install it? :)

**Comment by PEMapModder** [comment]
Did I say that it works?

**Comment by mwvent** [comment]
Am I right in thinking Amoeba is the only in-development MCPE proxy right now?

I was using fast-transfer but only to immediately move the players from my web/database server over to the one that runs the actual server instance. My emergency plan was when 0.13 comes out and turns out not to support fasttransfer was to use iptables instead to route the traffic over the LAN between the two servers effectively wasting the second servers public internet interface but providing a working solution. 
So a warning to anybody who was going to try this - In reality this works awfully - The Pocketmine server sees all traffic as coming from the one IP - Raklib decides to constantly block that one IP for some reason and to the game is unplayable.

Had to change it again so the instance of pocketmine running on the webserver kicks players with a message telling them to use the subdomain name for the other instance instead to connect. Ill call it slowtransfer :-)

**Comment by reidq7** [comment]
Yeah I'm going to have to resort to just telling players to add the ips as well :(

**Comment by mwvent** [comment]
It's just unfortunate some people do not like reading - my re-director servers log looks like..

[11:40:32] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged in with entity id 3 at (lobby, 128, 71, 128)
[11:40:33] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged out due to Kicked by admin. Reason: Please connect to pm1.wattz.org.uk port 19132 instead
[11:40:38] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged in with entity id 4 at (lobby, 128, 71, 128)
[11:40:38] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged out due to Kicked by admin. Reason: Please connect to pm1.wattz.org.uk port 19132 instead
[11:40:45] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged in with entity id 5 at (lobby, 128, 71, 128)
[11:40:46] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged out due to Kicked by admin. Reason: Please connect to pm1.wattz.org.uk port 19132 instead
[11:40:51] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged in with entity id 6 at (lobby, 128, 71, 128)
[11:40:52] [Server thread/INFO]: hootto[/86.10.124.246:1047] logged out due to Kicked by admin. Reason: Please connect to pm1.wattz.org.uk port 19132 instead

If Amoeba takes off Id have the actual lobby world running on the main domain's server with the web server and the second server also with Amoeba at the frontend port and a proxy for http/s traffic to the web server through the LAN between the two servers. I could use round robin DNS to get plenty of public bandwidth. That is the plan anyway. I'm glad I kept my worlds running on one instance now, I was a little envious of ones that were brave enough to use a whole net of fasttransfers now I feel sorry for them

**Comment by PEMapModder** [comment]
The principle of Amoeba (Amoeba server) is that it is a standalone server, and "Pods" (child servers) will create a TCP connection to Amoeba for exchanging data. Also, Amoeba will assign integer pod IDs to pods, then will transfer the clients to a certain server via an internal event handling API.

**Comment by legoboy0215** [comment]
Why would Mojang / Microsoft even remove the packet?

**Comment by deotern** [comment]
I seen something like this before, but i forgot where:
because of security problem
